import type { Property, MarketOpportunity, SecretVenture, PropertyGroup } from './types';

// ============================================================
// Standard US Monopoly Board Data
// ============================================================

export const INITIAL_PROPERTIES: Property[] = [
  // ── Brown ──────────────────────────────────────────────────
  {
    id: 'mediterranean_avenue',
    name: 'Mediterranean Avenue',
    group: 'Brown',
    price: 60,
    baseRent: 2,
    rentWithMonopoly: 4,
    rentByHouseCount: [10, 30, 90, 160],
    rentWithHotel: 250,
    houseCost: 50,
    mortgageValue: 30,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'baltic_avenue',
    name: 'Baltic Avenue',
    group: 'Brown',
    price: 60,
    baseRent: 4,
    rentWithMonopoly: 8,
    rentByHouseCount: [20, 60, 180, 320],
    rentWithHotel: 450,
    houseCost: 50,
    mortgageValue: 30,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Light Blue ─────────────────────────────────────────────
  {
    id: 'oriental_avenue',
    name: 'Oriental Avenue',
    group: 'LightBlue',
    price: 100,
    baseRent: 6,
    rentWithMonopoly: 12,
    rentByHouseCount: [30, 90, 270, 400],
    rentWithHotel: 550,
    houseCost: 50,
    mortgageValue: 50,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'vermont_avenue',
    name: 'Vermont Avenue',
    group: 'LightBlue',
    price: 100,
    baseRent: 6,
    rentWithMonopoly: 12,
    rentByHouseCount: [30, 90, 270, 400],
    rentWithHotel: 550,
    houseCost: 50,
    mortgageValue: 50,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'connecticut_avenue',
    name: 'Connecticut Avenue',
    group: 'LightBlue',
    price: 120,
    baseRent: 8,
    rentWithMonopoly: 16,
    rentByHouseCount: [40, 100, 300, 450],
    rentWithHotel: 600,
    houseCost: 50,
    mortgageValue: 60,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Pink ───────────────────────────────────────────────────
  {
    id: 'st_charles_place',
    name: 'St. Charles Place',
    group: 'Pink',
    price: 140,
    baseRent: 10,
    rentWithMonopoly: 20,
    rentByHouseCount: [50, 150, 450, 625],
    rentWithHotel: 750,
    houseCost: 100,
    mortgageValue: 70,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'states_avenue',
    name: 'States Avenue',
    group: 'Pink',
    price: 140,
    baseRent: 10,
    rentWithMonopoly: 20,
    rentByHouseCount: [50, 150, 450, 625],
    rentWithHotel: 750,
    houseCost: 100,
    mortgageValue: 70,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'virginia_avenue',
    name: 'Virginia Avenue',
    group: 'Pink',
    price: 160,
    baseRent: 12,
    rentWithMonopoly: 24,
    rentByHouseCount: [60, 180, 500, 700],
    rentWithHotel: 900,
    houseCost: 100,
    mortgageValue: 80,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Orange ─────────────────────────────────────────────────
  {
    id: 'st_james_place',
    name: 'St. James Place',
    group: 'Orange',
    price: 180,
    baseRent: 14,
    rentWithMonopoly: 28,
    rentByHouseCount: [70, 200, 550, 750],
    rentWithHotel: 950,
    houseCost: 100,
    mortgageValue: 90,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'tennessee_avenue',
    name: 'Tennessee Avenue',
    group: 'Orange',
    price: 180,
    baseRent: 14,
    rentWithMonopoly: 28,
    rentByHouseCount: [70, 200, 550, 750],
    rentWithHotel: 950,
    houseCost: 100,
    mortgageValue: 90,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'new_york_avenue',
    name: 'New York Avenue',
    group: 'Orange',
    price: 200,
    baseRent: 16,
    rentWithMonopoly: 32,
    rentByHouseCount: [80, 220, 600, 800],
    rentWithHotel: 1000,
    houseCost: 100,
    mortgageValue: 100,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Red ────────────────────────────────────────────────────
  {
    id: 'kentucky_avenue',
    name: 'Kentucky Avenue',
    group: 'Red',
    price: 220,
    baseRent: 18,
    rentWithMonopoly: 36,
    rentByHouseCount: [90, 250, 700, 875],
    rentWithHotel: 1050,
    houseCost: 150,
    mortgageValue: 110,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'indiana_avenue',
    name: 'Indiana Avenue',
    group: 'Red',
    price: 220,
    baseRent: 18,
    rentWithMonopoly: 36,
    rentByHouseCount: [90, 250, 700, 875],
    rentWithHotel: 1050,
    houseCost: 150,
    mortgageValue: 110,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'illinois_avenue',
    name: 'Illinois Avenue',
    group: 'Red',
    price: 240,
    baseRent: 20,
    rentWithMonopoly: 40,
    rentByHouseCount: [100, 300, 750, 925],
    rentWithHotel: 1100,
    houseCost: 150,
    mortgageValue: 120,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Yellow ─────────────────────────────────────────────────
  {
    id: 'atlantic_avenue',
    name: 'Atlantic Avenue',
    group: 'Yellow',
    price: 260,
    baseRent: 22,
    rentWithMonopoly: 44,
    rentByHouseCount: [110, 330, 800, 975],
    rentWithHotel: 1150,
    houseCost: 150,
    mortgageValue: 130,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'ventnor_avenue',
    name: 'Ventnor Avenue',
    group: 'Yellow',
    price: 260,
    baseRent: 22,
    rentWithMonopoly: 44,
    rentByHouseCount: [110, 330, 800, 975],
    rentWithHotel: 1150,
    houseCost: 150,
    mortgageValue: 130,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'marvin_gardens',
    name: 'Marvin Gardens',
    group: 'Yellow',
    price: 280,
    baseRent: 24,
    rentWithMonopoly: 48,
    rentByHouseCount: [120, 360, 850, 1025],
    rentWithHotel: 1200,
    houseCost: 150,
    mortgageValue: 140,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Green ──────────────────────────────────────────────────
  {
    id: 'pacific_avenue',
    name: 'Pacific Avenue',
    group: 'Green',
    price: 300,
    baseRent: 26,
    rentWithMonopoly: 52,
    rentByHouseCount: [130, 390, 900, 1100],
    rentWithHotel: 1275,
    houseCost: 200,
    mortgageValue: 150,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'north_carolina_avenue',
    name: 'North Carolina Avenue',
    group: 'Green',
    price: 300,
    baseRent: 26,
    rentWithMonopoly: 52,
    rentByHouseCount: [130, 390, 900, 1100],
    rentWithHotel: 1275,
    houseCost: 200,
    mortgageValue: 150,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'pennsylvania_avenue',
    name: 'Pennsylvania Avenue',
    group: 'Green',
    price: 320,
    baseRent: 28,
    rentWithMonopoly: 56,
    rentByHouseCount: [150, 450, 1000, 1200],
    rentWithHotel: 1400,
    houseCost: 200,
    mortgageValue: 160,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Dark Blue ──────────────────────────────────────────────
  {
    id: 'park_place',
    name: 'Park Place',
    group: 'DarkBlue',
    price: 350,
    baseRent: 35,
    rentWithMonopoly: 70,
    rentByHouseCount: [175, 500, 1100, 1300],
    rentWithHotel: 1500,
    houseCost: 200,
    mortgageValue: 175,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'boardwalk',
    name: 'Boardwalk',
    group: 'DarkBlue',
    price: 400,
    baseRent: 50,
    rentWithMonopoly: 100,
    rentByHouseCount: [200, 600, 1400, 1700],
    rentWithHotel: 2000,
    houseCost: 200,
    mortgageValue: 200,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Railroads ─────────────────────────────────────────────
  {
    id: 'reading_railroad',
    name: 'Reading Railroad',
    group: 'Railroad',
    price: 200,
    baseRent: 25,
    rentWithMonopoly: 50,
    rentByHouseCount: [100, 200, 0, 0], // 3-owned=100, 4-owned=200 (stored in byHouseCount slots 0-3 but we use custom logic)
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 100,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'pennsylvania_railroad',
    name: 'Pennsylvania Railroad',
    group: 'Railroad',
    price: 200,
    baseRent: 25,
    rentWithMonopoly: 50,
    rentByHouseCount: [100, 200, 0, 0],
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 100,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'bo_railroad',
    name: 'B&O Railroad',
    group: 'Railroad',
    price: 200,
    baseRent: 25,
    rentWithMonopoly: 50,
    rentByHouseCount: [100, 200, 0, 0],
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 100,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'short_line',
    name: 'Short Line',
    group: 'Railroad',
    price: 200,
    baseRent: 25,
    rentWithMonopoly: 50,
    rentByHouseCount: [100, 200, 0, 0],
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 100,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  // ── Utilities ─────────────────────────────────────────────
  {
    id: 'electric_company',
    name: 'Electric Company',
    group: 'Utility',
    price: 150,
    baseRent: 0, // 4x dice roll (1 utility), 10x (both) — handled in engine
    rentWithMonopoly: 0,
    rentByHouseCount: [0, 0, 0, 0],
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 75,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
  {
    id: 'water_works',
    name: 'Water Works',
    group: 'Utility',
    price: 150,
    baseRent: 0,
    rentWithMonopoly: 0,
    rentByHouseCount: [0, 0, 0, 0],
    rentWithHotel: 0,
    houseCost: 0,
    mortgageValue: 75,
    ownerId: null, houses: 0, hasHotel: false, isMortgaged: false,
  },
];

export const RAILROAD_IDS = ['reading_railroad', 'pennsylvania_railroad', 'bo_railroad', 'short_line'];
export const UTILITY_IDS = ['electric_company', 'water_works'];

export const GROUP_SIZES: Record<string, number> = {
  Brown: 2,
  LightBlue: 3,
  Pink: 3,
  Orange: 3,
  Red: 3,
  Yellow: 3,
  Green: 3,
  DarkBlue: 2,
  Railroad: 4,
  Utility: 2,
};

export const STARTING_CASH = 1500;
export const GO_AMOUNT = 200;
export const BANK_HOUSE_SUPPLY = 32;
export const BANK_HOTEL_SUPPLY = 12;

// Board sides (for Franchisee venture — 2 properties on each side)
// Side 1: Go→Jail (indices 0–9 on board), Side 2: Jail→Free Parking, etc.
export const BOARD_SIDES: PropertyGroup[][] = [
  ['Brown', 'LightBlue'],   // Side 1: Mediterranean → Connecticut
  ['Pink', 'Orange'],        // Side 2: St. Charles → New York
  ['Red', 'Yellow'],         // Side 3: Kentucky → Marvin Gardens
  ['Green', 'DarkBlue'],     // Side 4: Pacific → Boardwalk
];

export const SECRET_VENTURES: SecretVenture[] = [
  {
    id: 'diplomatic_immunity',
    name: 'Diplomatic Immunity',
    achievementDescription: 'Reach $3,000 liquid cash at any point (does not need to be maintained).',
    effectDescription: 'Cannot be sent to Jail for any reason for the rest of the game.',
  },
  {
    id: 'corporate_sponsor',
    name: 'Corporate Sponsor',
    achievementDescription: 'Collect rent from every other remaining player at least once. (If the last uncollected player is eliminated, venture is auto-completed.)',
    effectDescription: 'Receives 1.5× the normal GO amount whenever passing GO.',
  },
  {
    id: 'franchisee',
    name: 'Franchisee',
    achievementDescription: 'Own at least 2 properties on each of the 4 sides of the board.',
    effectDescription: 'Rent on one chosen opposing monopoly is permanently halved when this player pays it.',
  },
  {
    id: 'conductor',
    name: 'Conductor',
    achievementDescription: 'Own all 4 Railroads.',
    effectDescription: 'When landing on any Railroad, may teleport to any other Railroad instead of collecting GO money for that pass.',
  },
  {
    id: 'luck_of_the_draw',
    name: 'Luck of the Draw',
    achievementDescription: 'Draw a combined 3 Chance and/or Community Chest cards.',
    effectDescription: 'May skip rolling dice and instead draw a Chance or Community Chest card on future turns.',
  },
  {
    id: 'utility_provider',
    name: 'Utility Provider',
    achievementDescription: 'Own both Utilities.',
    effectDescription: 'All players landing on either Utility pay the combined rent (10× dice roll, as if both utilities are owned).',
  },
  {
    id: 'slum_lord',
    name: 'Slum Lord',
    achievementDescription: 'Own the full Brown monopoly.',
    effectDescription: 'First house on each Brown property is free (still decrements supply). All house/hotel construction costs 50% off.',
  },
  {
    id: 'city_planner',
    name: 'City Planner',
    achievementDescription: 'Own $1,500+ worth of properties (sum of purchase prices).',
    effectDescription: 'Before moving, may choose to move the full sum of both dice OR only one die\'s value.',
  },
];

export const MARKET_OPPORTUNITIES: MarketOpportunity[] = [
  { id: 'mo_first_monopoly',         title: '1. First Monopoly',              description: 'First player to complete a color monopoly.',              claimedBy: null, rewardType: 'cash',       rewardAmount: 100 },
  { id: 'mo_own_8_properties',       title: '2. Own 8 Properties',            description: 'First player to own 8 properties.',                       claimedBy: null, rewardType: 'cash',       rewardAmount: 150,  threshold: 8 },
  { id: 'mo_own_12_properties',      title: '3. Own 12 Properties',           description: 'First player to own 12 properties.',                      claimedBy: null, rewardType: 'cash',       rewardAmount: 200,  threshold: 12 },
  { id: 'mo_first_house',            title: '4. First House Built',           description: 'First house built in the entire game.',                   claimedBy: null, rewardType: 'cash',       rewardAmount: 50 },
  { id: 'mo_build_3_houses',         title: '5. Build 3 Houses (cumulative)', description: 'First player to build 3 houses (cumulative).',            claimedBy: null, rewardType: 'cash',       rewardAmount: 100,  threshold: 3 },
  { id: 'mo_build_6_houses',         title: '6. Build 6 Houses (cumulative)', description: 'First player to build 6 houses (cumulative).',            claimedBy: null, rewardType: 'cash',       rewardAmount: 150,  threshold: 6 },
  { id: 'mo_first_hotel',            title: '7. First Hotel Built',           description: 'First hotel built — grants 1 free house on lowest monopoly.', claimedBy: null, rewardType: 'free_house' },
  { id: 'mo_build_3_hotels',         title: '8. Build 3 Hotels (cumulative)', description: 'First player to build 3 hotels (cumulative) — grants 1 free house.', claimedBy: null, rewardType: 'free_house', threshold: 3 },
  { id: 'mo_own_4_railroads',        title: '9. Own All 4 Railroads',         description: 'First player to own all 4 Railroads.',                    claimedBy: null, rewardType: 'cash',       rewardAmount: 150 },
  { id: 'mo_own_both_utilities',     title: '10. Own Both Utilities',         description: 'First player to own both Utilities.',                     claimedBy: null, rewardType: 'cash',       rewardAmount: 75 },
  { id: 'mo_complete_3_trades',      title: '11. Complete 3 Trades',          description: 'First player to complete 3 trades.',                      claimedBy: null, rewardType: 'cash',       rewardAmount: 100,  threshold: 3 },
  { id: 'mo_rent_from_3_players',    title: '12. Collect Rent from 3 Players',description: 'First player to collect rent from 3 different players.',  claimedBy: null, rewardType: 'cash',       rewardAmount: 50,   threshold: 3 },
  { id: 'mo_rent_from_6_players',    title: '13. Collect Rent from 6 Players',description: 'First player to collect rent from 6 different players.',  claimedBy: null, rewardType: 'cash',       rewardAmount: 100,  threshold: 6 },
  { id: 'mo_draw_3_chance',          title: '14. Draw 3 Chance Cards',        description: 'First player to draw 3 Chance cards — grants a Roll Again token.', claimedBy: null, rewardType: 'roll_again', threshold: 3 },
  { id: 'mo_draw_3_community_chest', title: '15. Draw 3 Community Chest Cards',description: 'First player to draw 3 Community Chest cards — grants a Roll Again token.', claimedBy: null, rewardType: 'roll_again', threshold: 3 },
  { id: 'mo_win_3_auctions',         title: '16. Win 3 Auctions',             description: 'First player to win 3 auctions.',                         claimedBy: null, rewardType: 'cash',       rewardAmount: 50,   threshold: 3 },
  { id: 'mo_win_6_auctions',         title: '17. Win 6 Auctions',             description: 'First player to win 6 auctions.',                         claimedBy: null, rewardType: 'cash',       rewardAmount: 100,  threshold: 6 },
  { id: 'mo_pass_go_3_times',        title: '18. Pass GO 3 Times',            description: 'First player to pass GO 3 times.',                        claimedBy: null, rewardType: 'cash',       rewardAmount: 50,   threshold: 3 },
  { id: 'mo_go_to_jail_3_times',     title: '19. Go to Jail 3 Times',         description: 'First player to go to jail 3 times — grants a GOOJF card.', claimedBy: null, rewardType: 'goojf',   threshold: 3 },
  { id: 'mo_first_free_parking',     title: '20. First Free Parking Landing', description: 'First player to ever land on Free Parking — $100 from bank.', claimedBy: null, rewardType: 'cash', rewardAmount: 100 },
];
